### ISSUE TITLE
`raise_from_error` doesn't always raise from error

### ISSUE THREAD

**Issue by chadwhitacre** [oauthlib/oauthlib#289] opened 2014-10-30 13:03 UTC
Over at https://github.com/gratipay/gratipay.com/issues/2869 we're seeing that [`raise_from_error`](https://github.com/idan/oauthlib/blob/04631866c058defb480462db1ec13cb7f88780a9/oauthlib/oauth2/rfc6749/errors.py#L249-L259) sometimes doesn't raise from the error. Here's the `params` in question:

```
{'error': {'type': u'OAuthException', 'message': u'This authorization code has been used.', 'code': 100}}
```

It looks like `raise_from_error` expects `error` to be a simple string, not a dictionary. How did it get to be a dictionary? One clue: we're seeing this when interacting with Facebook. Please let me know what other information might be helpful and I'll try to provide it.

Zooming out: I would expect `raise_from_error` never to not raise. It should always raise. I would expect a fallback exception, maybe something like `UnknownOAuth2Error`, if no other `OAuth2Error` matches.

P.S. As an aside (I can reticket separately if you like), `params.get` on [line 253](https://github.com/idan/oauthlib/blob/04631866c058defb480462db1ec13cb7f88780a9/oauthlib/oauth2/rfc6749/errors.py#L253) will fail with an `AttributeError` if `params` is `None`, which is the default value for that function parameter.

**Comment by JonathanHuot** [comment] 2018-08-14 22:48
duplicate of https://github.com/oauthlib/oauthlib/issues/431

**Closed by JonathanHuot** 2018-08-14 22:48 UTC
